
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from django.template.loader import get_template
# from xhtml2pdf import pisa
from io import BytesIO


styles=getSampleStyleSheet()
title=styles["Heading1"]
title.alignment=TA_CENTER
heading=styles["Heading2"]
normal=styles["BodyText"]

def _summary_table(quiz):
    data=[
        ["MCQ",quiz.mcq_score],
        ["Theory",quiz.theory_score],
        ["Total",quiz.total_score],
        ["Percentage",f"{quiz.percentage}%"],
    ]
    t=Table(data,colWidths=[2.5*inch,2.5*inch])
    t.setStyle(TableStyle([
        ("GRID",(0,0),(-1,-1),0.5,colors.grey),
        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#E8F0FE")),
    ]))
    return t

def generate_result_pdf(quiz):
    buf=BytesIO()
    doc=SimpleDocTemplate(buf)
    story=[]
    story.append(Paragraph("AiQuiz Generated by GM",title))
    story.append(Paragraph("Assessment Report",heading))
    story.append(Spacer(1,12))
    story.append(Paragraph(f"<b>Name:</b> {quiz.user.get_full_name() or quiz.user.username}",normal))
    story.append(Paragraph(f"<b>Email:</b> {quiz.user.email}",normal))
    story.append(Paragraph(f"<b>Topic:</b> {quiz.topic}",normal))
    story.append(Spacer(1,12))
    story.append(_summary_table(quiz))
    doc.build(story)
    pdf=buf.getvalue()
    buf.close()
    return pdf
