# Generated by Django 6.0.7 on 2026-07-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_score_quiz_mcq_score_quiz_quiz_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='quiz',
            name='ai_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quiz',
            name='mcq_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='theory_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
    ]
