# Generated by Django 6.0.7 on 2026-07-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quiz_options_quiz_ai_feedback_quiz_mcq_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'MCQ'), ('THEORY', 'THEORY')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_questions', to='quiz.uploadedpdf')),
            ],
            options={
                'unique_together': {('pdf', 'question')},
            },
        ),
    ]
